apiVersion: v1
kind: Pod
metadata:
  name: birdsquawk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: birdsquawk
  template:
    metadata:
      labels: 
        app: birdsquawk
    spec:
      containers:
        - name: birdsquawk
          image: kashish04/birdsquawk
---
apiVersion: v1
kind: Service
metadata:
  name: birdsquawk-service
spec:
  selector:
    app: birdsquawk
  ports: 
    - name: birdsquawk
      protocol: TCP
      port: 5000
      targetPort: 5000
